@extends('layouts.app')

@section('title', "{$meta['name']} — Report")
@section('heading', 'Report preview')

@section('content')
    <div class="mb-4">
        <a href="{{ route('reports.show', $reportType) }}" class="link text-sm inline-flex items-center gap-1">
            <x-icon name="arrow-left" class="w-3.5 h-3.5" />
            Back to parameters
        </a>
    </div>

    <x-page-header title="{{ $meta['name'] }}" subtitle="Generated report preview drawn from stored payroll data (FR-5.3).">
        <x-slot:actions>
            <a href="{{ route('reports.export.pdf', array_merge(['reportType' => $reportType], $params)) }}" class="btn btn-secondary btn-sm" target="_blank">
                <x-icon name="printer" class="w-3.5 h-3.5" />
                Export PDF
            </a>
            <a href="{{ route('reports.export.excel', array_merge(['reportType' => $reportType], $params)) }}" class="btn btn-secondary btn-sm">
                <x-icon name="download" class="w-3.5 h-3.5" />
                Export Excel
            </a>
        </x-slot:actions>
    </x-page-header>

    {{-- Provisional watermark banner if unfinalized (AC-5.3.5) --}}
    @if ($data['is_provisional'])
        <div class="mb-6 p-4 rounded-lg bg-amber-50 border-2 border-amber-300 text-amber-900 flex items-start gap-3">
            <span class="inline-flex items-center justify-center px-2 py-1 rounded bg-amber-200 text-amber-900 font-bold text-xs uppercase tracking-wider">
                PROVISIONAL
            </span>
            <div>
                <p class="font-semibold text-sm">Provisional Report (AC-5.3.5)</p>
                <p class="text-xs mt-0.5">
                    This report reflects payroll run #{{ $data['run']->payroll_run_id }} which is currently in <strong>{{ $data['run']->run_status }}</strong> status.
                    Official payslips and statutory remittances can only be finalized from a Finalized payroll run.
                </p>
            </div>
        </div>
    @endif

    {{-- Report Header Box --}}
    <x-card class="mb-6">
        <div class="border-b border-line pb-4 mb-4 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">
            <div>
                <h2 class="text-lg font-bold text-ink">{{ $data['org']?->registered_name ?? config('app.name', 'Municipal Payroll System') }}</h2>
                <p class="text-sm font-semibold text-brand-900 mt-0.5">{{ $meta['name'] }}</p>
            </div>
            <div class="text-left sm:text-right text-xs text-ink-muted">
                <p>Generated: <span class="font-medium text-ink tabular">{{ $generatedAt->format('Y-m-d H:i:s') }}</span></p>
                <p>Generated by: <span class="font-medium text-ink">{{ $generatedBy->username }}</span> ({{ $generatedBy->role?->role_name }})</p>
            </div>
        </div>

        <div class="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs">
            @foreach ($data['parameters'] as $label => $val)
                <div>
                    <span class="text-ink-muted font-medium">{{ $label }}:</span>
                    <span class="text-ink ml-1 font-semibold">{{ $val }}</span>
                </div>
            @endforeach
        </div>
    </x-card>

    {{-- Report Content --}}
    @if ($reportType === 'payroll_register')
        {{-- Summary Stats --}}
        <div class="grid grid-cols-1 sm:grid-cols-4 gap-4 mb-6">
            <x-stat label="Employee headcount" :value="$data['totals']['employee_count']" />
            <x-stat label="Total gross pay" :value="'₱' . number_format((float) $data['totals']['gross_pay'], 2)" />
            <x-stat label="Total deductions" :value="'₱' . number_format((float) $data['totals']['total_deductions'], 2)" />
            <x-stat label="Total net pay" :value="'₱' . number_format((float) $data['totals']['net_pay'], 2)" />
        </div>

        <x-card :flush="true">
            <x-table>
                <x-slot:head>
                    <th>Employee No</th>
                    <th>Employee Name</th>
                    <th>Department</th>
                    <th class="num">Days</th>
                    <th class="num">Gross pay</th>
                    <th class="num">Deductions</th>
                    <th class="num">Net pay</th>
                </x-slot:head>
                @foreach ($data['lines'] as $line)
                    @php
                        $dept = $line->employee?->currentEmploymentDetail?->department?->department_name ?? '—';
                    @endphp
                    <tr>
                        <td class="tabular font-medium text-xs">{{ $line->employee?->employee_no }}</td>
                        <td class="font-medium text-ink">{{ $line->employee?->fullName() }}</td>
                        <td class="text-xs text-ink-muted">{{ $dept }}</td>
                        <td class="num tabular text-xs">{{ number_format((float) $line->days_worked, 2) }}</td>
                        <td class="num tabular font-mono text-xs">₱{{ number_format((float) $line->gross_pay, 2) }}</td>
                        <td class="num tabular font-mono text-xs text-amber-700">₱{{ number_format((float) $line->total_deductions, 2) }}</td>
                        <td class="num tabular font-mono text-xs font-semibold text-emerald-700">₱{{ number_format((float) $line->net_pay, 2) }}</td>
                    </tr>
                @endforeach
                <tr class="bg-slate-50 font-bold">
                    <td colspan="3" class="text-ink">TOTALS (AC-5.3.2 Reconciled)</td>
                    <td class="num tabular text-xs">{{ number_format((float) $data['totals']['days_worked'], 2) }}</td>
                    <td class="num tabular font-mono text-xs text-ink">₱{{ number_format((float) $data['totals']['gross_pay'], 2) }}</td>
                    <td class="num tabular font-mono text-xs text-amber-700">₱{{ number_format((float) $data['totals']['total_deductions'], 2) }}</td>
                    <td class="num tabular font-mono text-xs text-emerald-700">₱{{ number_format((float) $data['totals']['net_pay'], 2) }}</td>
                </tr>
            </x-table>
        </x-card>
    @elseif ($reportType === 'payroll_summary')
        {{-- Department Summaries --}}
        <div class="mb-6">
            <h3 class="text-sm font-semibold text-ink mb-2">Department Totals</h3>
            <x-card :flush="true">
                <x-table>
                    <x-slot:head>
                        <th>Department</th>
                        <th class="num">Headcount</th>
                        <th class="num">Gross pay</th>
                        <th class="num">Total deductions</th>
                        <th class="num">Net pay</th>
                    </x-slot:head>
                    @foreach ($data['department_summaries'] as $ds)
                        <tr>
                            <td class="font-medium text-ink">{{ $ds['department'] }}</td>
                            <td class="num tabular">{{ $ds['headcount'] }}</td>
                            <td class="num tabular font-mono">₱{{ number_format((float) $ds['gross_pay'], 2) }}</td>
                            <td class="num tabular font-mono text-amber-700">₱{{ number_format((float) $ds['total_deductions'], 2) }}</td>
                            <td class="num tabular font-mono font-semibold text-emerald-700">₱{{ number_format((float) $ds['net_pay'], 2) }}</td>
                        </tr>
                    @endforeach
                    <tr class="bg-slate-50 font-bold">
                        <td class="text-ink">TOTALS</td>
                        <td class="num tabular">{{ $data['totals']['employee_count'] }}</td>
                        <td class="num tabular font-mono text-ink">₱{{ number_format((float) $data['totals']['gross_pay'], 2) }}</td>
                        <td class="num tabular font-mono text-amber-700">₱{{ number_format((float) $data['totals']['total_deductions'], 2) }}</td>
                        <td class="num tabular font-mono text-emerald-700">₱{{ number_format((float) $data['totals']['net_pay'], 2) }}</td>
                    </tr>
                </x-table>
            </x-card>
        </div>

        {{-- Categories --}}
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <x-card title="Earning categories" :flush="true">
                <x-table>
                    <x-slot:head>
                        <th>Category</th>
                        <th class="num">Amount</th>
                    </x-slot:head>
                    @foreach ($data['earning_totals'] as $name => $amt)
                        <tr>
                            <td class="font-medium text-ink">{{ $name }}</td>
                            <td class="num tabular font-mono">₱{{ number_format((float) $amt, 2) }}</td>
                        </tr>
                    @endforeach
                </x-table>
            </x-card>

            <x-card title="Deduction categories" :flush="true">
                <x-table>
                    <x-slot:head>
                        <th>Category</th>
                        <th class="num">Amount</th>
                    </x-slot:head>
                    @foreach ($data['deduction_totals'] as $name => $amt)
                        <tr>
                            <td class="font-medium text-ink">{{ $name }}</td>
                            <td class="num tabular font-mono text-amber-700">₱{{ number_format((float) $amt, 2) }}</td>
                        </tr>
                    @endforeach
                </x-table>
            </x-card>
        </div>
    @endif
@endsection
