<div class="payslip">
    <div class="header">
        <table style="border: 0; margin-top: 0;">
            <tr>
                <td style="border: 0;">
                    <div class="brand">
                        @if ($payslip['org']['logo_uri'])
                            <img src="{{ $payslip['org']['logo_uri'] }}" class="logo" alt="Logo" />
                        @endif
                        <div>
                            <div class="org-name">{{ $payslip['org']['name'] }}</div>
                            <div class="org-address">{{ $payslip['org']['address'] }}</div>
                        </div>
                    </div>
                </td>
                <td style="border: 0; text-align: right;">
                    <div class="title">{{ $payslip['label'] }}</div>
                    <div class="period-line">{{ $payslip['period'] }}</div>
                    <div class="period-line">{{ $payslip['cutoff'] }}</div>
                    <div class="period-line">Pay date: {{ $payslip['pay_date'] }}</div>
                </td>
            </tr>
        </table>
    </div>

    <table>
        <tr>
            <th style="width: 18%;">Employee no.</th>
            <td style="width: 32%;">{{ $payslip['employee']['no'] }}</td>
            <th style="width: 18%;">Name</th>
            <td>{{ $payslip['employee']['name'] }}</td>
        </tr>
        <tr>
            <th>Department</th>
            <td>{{ $payslip['employee']['department'] }}</td>
            <th>Position</th>
            <td>{{ $payslip['employee']['position'] }}</td>
        </tr>
        <tr>
            <th>Employment status</th>
            <td colspan="3">{{ $payslip['employee']['status'] }}</td>
        </tr>
    </table>

    <table>
        <caption class="caption">Earnings</caption>
        <thead>
            <tr>
                <th style="width: 34%;">Item</th>
                <th style="width: 44%;">Detail</th>
                <th style="width: 22%;" class="num">Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($payslip['earnings'] as $earning)
                <tr>
                    <td>
                        {{ $earning['name'] }}
                        @if ($earning['is_taxable'])
                            <span class="tag">(taxable)</span>
                        @endif
                    </td>
                    <td>{{ $earning['detail'] }}</td>
                    <td class="num">{{ $earning['amount'] }}</td>
                </tr>
            @empty
                <tr><td colspan="3" class="muted">No earnings recorded.</td></tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr>
                <th colspan="2" class="strong">Gross Pay</th>
                <td class="num strong">{{ $payslip['gross_pay'] }}</td>
            </tr>
        </tfoot>
    </table>

    <table>
        <caption class="caption">Deductions</caption>
        <thead>
            <tr>
                <th style="width: 34%;">Item</th>
                <th style="width: 44%;">Detail</th>
                <th style="width: 22%;" class="num">Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($payslip['deductions'] as $deduction)
                <tr>
                    <td>{{ $deduction['name'] }}</td>
                    <td>{{ $deduction['detail'] }}</td>
                    <td class="num">{{ $deduction['amount'] }}</td>
                </tr>
            @empty
                <tr><td colspan="3" class="muted">No deductions recorded.</td></tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr>
                <th colspan="2" class="strong">Total Deductions</th>
                <td class="num strong">{{ $payslip['total_deductions'] }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="net">NET PAY &nbsp;&nbsp;₱{{ $payslip['net_pay'] }}</div>

    <div class="footer">
        @if ($payslip['is_reprint'])
            <div class="reprint">REPRINT — reissued {{ $payslip['reprinted_at'] }} by {{ $payslip['reprinted_by'] }}</div>
        @endif
        <div>
            All figures are the accounting office's computed values imported from payroll register v{{ $payslip['import_version'] ?? '—' }},
            stored and rendered without recomputation by this system.
        </div>
        <div>Generated by the Municipal Payroll System on {{ $payslip['generated_at'] }}.</div>
    </div>
</div>